apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
spec:
  type: NodePort
  selector:
    app: nginx            # Must match the label on your nginx pod/deployment
  ports:
    - protocol: TCP
      port: 80             # Service port
      targetPort: 80      # Pod/container port (nginx listens on 80)
      nodePort: 30007  # Must match the extraPortMappings containerPort in kind-config.yml
